version: "3.9"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/backend/staticfiles
      - media_volume:/app/backend/mediafiles
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             uvicorn config.asgi:application --host 0.0.0.0 --port 8000"
    volumes:
      - ./backend:/app
      - ./documents:/app/documents
      - static_volume:/app/backend/staticfiles
      - media_volume:/app/backend/mediafiles
    env_file:
      - ./.env
    environment:
      - QDRANT_HOST=${QDRANT_HOST}
      - QDRANT_PORT=${QDRANT_PORT}
    depends_on:
      - qdrant
    # EC2가 RDS에 접근하므로 db 서비스는 필요 없음

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "${QDRANT_PORT}:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
      - ./documents:/qdrant/documents
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:
  qdrant_storage:
