version: "3.9"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"  # 8000 포트로 Nginx 접근
    depends_on:
      - backend
      - frontend

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./frontend/build:/app/frontend/build  # React 빌드 파일을 Django에 마운트
    ports:
      - "8001:8000"  # 백엔드는 8001 포트로 접근
    env_file:
      - ./.env
    depends_on:
      - db


  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"  # 프론트엔드는 3000 포트 유지
    environment:
      - REACT_APP_API_BASE_URL=http://localhost/api
    depends_on:
      - backend

  db:
    image: postgres:16.9
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data: 