version: "3.9"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./frontend/build:/app/frontend/build  # React 빌드 파일을 Django에 마운트
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  # frontend 서비스는 제거 - Django에서 React 앱을 직접 서빙

  db:
    image: postgres:16.9
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data: 